### ISSUE TITLE
Expand vertically in scroll areas

### ISSUE THREAD

**Issue by d3nw0** [marcusolsson/tui-go#104]
So I'm trying to create a responsive list, to do that i need a scroll area, but when a scroll area is added, the items don't expand vertically anymore. I'm not sure if this is a bug or it's like this by design.

**Comment by marcusolsson** [comment]
The ScrollArea, by design, is just a view (or a _window_) over a widget. The contained widget would expand into infinity since it's not constrained by the size of the ScrollArea, nor the size of the terminal. Widgets in a scroll area has its size set to its size hint. There was a proposal for constraining one dimension to the size of the scroll area, meaning it would only scroll horizontally or vertically (not both). Would this work for your use case?

**Comment by d3nw0** [comment]
Yeah, it will work for my use case, since I need the list to expand horizontally and I need the ScrollArea to scroll vertically.

**Comment by d3nw0** [comment]
I found a workaround for this case, by inheriting the ScrollArea using 
```
type myscrollarea struct {
    *tui.ScrollArea
}
```
and redefining `Scroll(), Draw(p *tui.Painter), Resize(size image.Point)` to fit your use case.
