### ISSUE TITLE
When a box has the focus change the color of the the border

### ISSUE THREAD

**Issue by yml** [marcusolsson/tui-go#20]
It would nice to signal the user which VBox / HBox has the focus. When the components is an `Entry` it is less of an issue but when the component is a `list` or a `button` it is harder to tell which component as the focus now.

For example in the tui below where is the focus now ?

![tui-go_where_is_the_focus_017-05-25 21-02-39](https://cloud.githubusercontent.com/assets/125902/26466037/96932080-418d-11e7-8b4d-7a89ceba3d87.png)

**Comment by marcusolsson** [comment]
The `Box` widget would have define its own style identifiers, like `Button` does here: https://github.com/marcusolsson/tui-go/blob/master/button.go#L29-L39. 

Basically, https://github.com/marcusolsson/tui-go/blob/master/box.go#L71 would need to be use the `p.WithStyle()` method. 

Here's how you would customize the styles: https://github.com/marcusolsson/tui-go/blob/master/example/color/main.go#L16-L18

If you're up for it, I think it should be fairly straightforward to implement. Otherwise I'll be able to take a look at it during the weekend! Thank you for these feature requests, I really appreciate them!

**Comment by yml** [comment]
@marcusolsson I think I understand direction you have given. I will try to give it a go in the coming days.

**Comment by marcusolsson** [comment]
Closed by #23

**Comment by marcusolsson** [comment]
Also created https://github.com/marcusolsson/tui-go/issues/24 based on the comments on the default theme.
