### ISSUE TITLE
Color support question

### ISSUE THREAD

**Issue by gonzaloserrano** [marcusolsson/tui-go#32]
First sorry if I bother you with so many questions!

I'd like to have different font colors in my list ('ala `tig` tool) using something like https://github.com/fatih/color#insert-into-noncolor-strings-sprintfunc, e.g:

```go
// ...
yellow := color.New(color.FgYellow).SprintFunc()
red := color.New(color.FgRed).SprintFunc()
return fmt.Sprintf("%s|%s|o %s", b.Author.When.String()[2:19], yellow(author), red(name))
// then I use the returned string as en element for `list.AddItems()
```

Unfortunately color codes are not rendered:

<img width="1131" alt="screenshot 2017-06-06 23 13 43" src="https://user-images.githubusercontent.com/349328/26852221-d81f0706-4b0d-11e7-8552-1f4dc19aaf2e.png">

Any idea if this is possible? (-:

**Comment by marcusolsson** [comment]
Unfortunately, color support is fairly limited right now. Setting colors with this granularity is currently not possible.

In the vision I have, all colors should be part of a theme to let users set their own color scheme. I've been playing with the idea to promote a common theme config file (e.g, a `~/.tuirc`) that can be reused across all tui-go application so that all your apps have the same look 'n feel.

In this vision, instead of hard coding colors for widgets, I think the solution would be to instead introduce custom theme identifiers. For example, like the "built-in" identifier `list.item.selected` ([example](https://github.com/marcusolsson/tui-go/blob/master/example/color/main.go#L17-L18)) you would add your own custom identifier, something like this:

```
l := tui.NewLabel("gonzaloserrano")
l.SetStyleName("author")
```

... and then, in `main.go`, you'd set the actual (default) colors.

```
theme.SetStyle("label.author", tui.Style{Bg: tui.ColorYellow, Fg: tui.ColorDefault})
```

In fact, this is how Vaadin supports custom CSS:
https://vaadin.com/api/7.7.6/com/vaadin/ui/Component.html#setStyleName-java.lang.String-

**Comment by marcusolsson** [comment]
... and you're definitely not bothering me with your questions! Questions like these let me better understand what's important to those using tui-go. They help me focus my efforts on things that matter. My ambition is to graduate tui-go from its experimental label and start working with releases, but before I can do that I want to feel comfortable enough with the API to avoid breaking people's code more than absolutely necessary.

So by all means, continue posting your questions/bugs/issues! I'll try to answer/fix them as timely as possible!

**Comment by gonzaloserrano** [comment]
Sounds awesome! 👍

**Comment by marcusolsson** [comment]
Couldn't resist trying out the idea of custom theme identifiers :) If you feel like trying it out, check out the updated `color` example!

**Comment by gonzaloserrano** [comment]
What was quick, and looks cool.

I think it can't use it for my list though, since lists are composed of strings and not labels or widgets. Maybe I'd need to implement some kind of list that supports labels in the same line or so. I'll think about it.

**Comment by marcusolsson** [comment]
Ah, right. Actually, I'd say the Table widget is probably what you're asking for (a list that's composed of widgets). I'll make sure to make add an example! :)

**Comment by gonzaloserrano** [comment]
Oh, that could make it. Actually I tried with the table but had an issue: moving with up/down arrow didn't work. Maybe I did something wrong.

**Comment by marcusolsson** [comment]
Yes, I introduced a bug when I "fixed" this issue before :( That should have been fixed as well by now. 

Although, while working on the example I mentioned, I realized that it might not be so easy after all. The styled label has currently higher priority than the selection theme which mean that the styled labels will still have black background even though they are selected.

Somehow, the `WithStyle` method needs to be aware of whether a theme with higher priority is currently applied. I think it's actually a rather fun problem so I will probably look at it tomorrow :) Sorry for getting your hopes up, hopefully I'll have it sorted out in a timely manner :)
