### ISSUE TITLE
Feature request/support: How can I set the color of the title/border on a vBox?

### ISSUE THREAD

**Issue by RPiAwesomeness** [marcusolsson/tui-go#38]
The theme documentation is a bit lacking in terms of what can and can't be themed, so I'm having trouble figuring out how to do this. I'd be definitely willing to submit a little pullreq if you want some documentation written around this.

I'm working off the chat example right now, and I have a sidebar for clients, but I want to set the theme for that. It's a vBox, how can I set the color for the vBox's label and for it's border. Is this possible, or is it something that's coming?

That, and along with it, is there a reference for what selectors work with `theme.SetStyle()`?

**Comment by RPiAwesomeness** [comment]
Okay, I figured out how to set it, but it sets the box as a whole, title and all, the same color. Can the title be set separately?

**Comment by marcusolsson** [comment]
Color/theming is one of the more underdeveloped parts of tui-go at this moment, hence the poor documentation :) However, I am starting to feel increasingly happy with the decision to go with selector-based theming for tui-go and documentation should probably reflect that.

Currently, the border is not treated differently than any other text. This makes it difficult to style them separately. On the top of my head, I see a couple of approaches to solve this:

__Border as selector:__

```go
theme.SetStyle("box", tui.Style{Fg: tui.ColorDefault, Bg: tui.ColorDefault})
theme.SetStyle("box.border", tui.Style{Fg: tui.ColorBlue, Bg: tui.ColorDefault})
```

__Border as style attribute:__

```go
theme.SetStyle("box", tui.Style{Fg: tui.ColorDefault, Bg: tui.ColorDefault, Border: tui.ColorBlue})
```

The latter would probably be more intuitive to someone with CSS experience, but it suggests that you could set a border on all widgets. Since only boxes, grids and tables have borders this might lead to unnecessary frustration.

The first one should be a easy-pick, changing [this] call to `WithStyle` into two calls with separate style names.

**Comment by RPiAwesomeness** [comment]
I would lean more towards the second one, because Fg/Bg/Border are optional (correct?) so if you don't include them, and have an example in the documentation without having that attribute set, then people would understand.

**Comment by marcusolsson** [comment]
Sorry for the late response!

You might be right, and I would actually happily accept a PR with either solution as I unfortunately won't be able to work on this myself anytime soon.

**Comment by marcusolsson** [comment]
I just want to mention that implementing the _border-as-style-attribute_ approach would involve quite substantial changes to how the `Style` is used, so for now I've decided to go with the first approach. I'm open to revisiting this in the future.
