### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by onerciller** [marcusolsson/tui-go#8]
hi can you prepare detailed documentation about  for example events,ui design , because it doesn't enough

**Comment by marcusolsson** [comment]
Thank you for your interest in tui-go! Unfortunately, the reason for the lack of proper documentation is because tui-go still is very much in an experimental at this point. Any documentation will likely be outdated fairly quickly. The current event handling mechanism is minimal at best, and something I hope to improve in a near future. 

That being said, I do value good documentation and will provide it as soon as I more confident about the design. If you have any specific questions, I'd be happy to answer them though!

**Comment by onerciller** [comment]
thank you for you reply I'll constantly follow you package.  I want to make terminal editor just like micro with your package, however i don't know how I will start since there is no document  have any recommendations ?

**Comment by marcusolsson** [comment]
That would be really cool :+1: So far, the main focus has been layout handling. More advanced support for text input (which would be needed to write an editor) is still yet to come. I'm currently working on multi-line text input and I will add an example for creating a _very_ basic text editor once that is done.

In the meantime, check out the [examples](https://github.com/marcusolsson/tui-go/tree/master/example), which would be the best way to learn tui-go at this point. Is it alright with you if I close this issue for now, giving you my word the I will make sure to add documentation once the API becomes more stable?

Also, I recommend that you follow https://github.com/marcusolsson/tui-go/issues/10, which might be interesting for your purposes.

**Comment by onerciller** [comment]
thanks for your support and recommendation , i will follow #10 issue and your api
