### ISSUE TITLE
Entry crashes when a character doesn't have space to be placed.

### ISSUE THREAD

**Issue by Danik32** [marcusolsson/tui-go#9]
In the Chat example, when you try to input more characters than the terminal width allows, the program panics with "panic: Parameter is  incorrect."

Expected behavior: Wouldn't allow to input more characters. (And wouldn't crash :D)

Offtopic: Awesome library, works better then most libs that I have tried. Would love to use it when it is out of the experimental state. :D

**Comment by marcusolsson** [comment]
Thanks for taking the time to report this! Unfortunately, I can't seem to reproduce the panic (or find the error you mentioned). The text entry happily accept the characters (although you don't actually get to see them :P ). Would you care to provide some more details?

I actually think the proper way to address this would be to accept more characters than it's width, but provide horizontal scrolling in case it won't fit the view. I will look into this!

Thanks for the kind words! I didn't anticipate the feedback I've gotten since writing this, and will make sure to find the time to further improve tui-go!

**Comment by Danik32** [comment]
The error is in the "Chat" example. My Go version: go1.7.3 windows/amd64

**Comment by Danik32** [comment]
Updated to Go 1.8, issue still there.
I think it tries to do termbox.SetCursor(x, y) with an incorrect parameter, and termbox returns the "Parameter is incorrect." error.

**Comment by marcusolsson** [comment]
Hm, I'm still unable to make it crash (can't even find where the error is defined). In the meantime, I've pushed https://github.com/marcusolsson/tui-go/commit/bfb4ff72a87503b347373bc267eeaca2a23d1cce that should restrict drawing of text and cursor to the width of the entry. Do you think you check to see if it makes any difference?

**Comment by Danik32** [comment]
Sorry for taking so long. Updated the library, issue fixed :D
